### ISSUE TITLE
Update README, current errors

### ISSUE THREAD

**Issue by hmgaudecker** [pytask-dev/vscode-pytask#2]
The README is what is being shown in the extension page within VS Code:

![image](https://github.com/mj023/pytask_vscode/assets/158456/b9ec9752-fb19-4567-a8c1-e75c5e843127)

Still has the ancient instructions for installation in there, confuses me each time I look at it until I find the "more info" part with the last release on the right :smile: 

Current version does not seem to work for me: 

![image](https://github.com/mj023/pytask_vscode/assets/158456/465674f6-6b37-43e3-b222-ba5ba69ef0c1)

**Comment by hmgaudecker** [comment]
Ah, so after poking around a bit, found https://github.com/mj023/pytask-plugin-vscode and 

    pip install git+https://github.com/mj023/pytask-plugin-vscode

does work. 

Not much happening, though:

![image](https://github.com/mj023/pytask_vscode/assets/158456/a197e453-516f-4535-8763-a7a968faee07)

**Comment by mj023** [comment]
Sorry, I just published this version to test it on different computers. Did not think anyone would notice 😅 . I was going to update the README etc. once I was confident that this new version of the Plugin works.

**Comment by hmgaudecker** [comment]
No worries! But I do use it every now and then already! :smile:

**Comment by mj023** [comment]
Thanks for using the Extension! It is quite concerning, that it stopped working though as I just tried it on a different Unix PC with the Research Template Example and did not have any problems. I just updated the Readme and maybe you could try it again with the Pytask Plugin installed from the PyPi Test Server.

**Comment by hmgaudecker** [comment]
I think it did actually work, it was just too hard for this old man to find the outputs... I never have that output window open and did not realize there was a pull-down menu. Apologies!!!

This said, even if it succeeds, there sometimes is a message popping up that it did not succeed. And there are always complaints about no test framework being configured (in a project that is the backbone of a course, so no tests at all).
